# Generated by Django 2.2.2 on 2020-01-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_from',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='exp',
            new_name='experience',
        ),
    ]
